### ISSUE TITLE
Il manque un élément `child` dans l'HTML

### ISSUE THREAD

**Issue by tzi** [t13h37/feedback-zilliox-flexbox#1]
Hello !

A la page 15 du livre, il y a le code source HTML des démos : 
```html
<div class=”parent”>
	 <div class=”child”>1</div>
	 <div class=”child”>2</div>
	 <div class=”child”>3</div>
	 <div class=”child”>4</div>
</div>
```
Dans cette démo, il y a 4 enfants et dans les démos suivantes il y en a 5.

A bientôt,
Thomas.

**Comment by pouipouidesign** [comment]
Corrigé dans la v1.1 que nous venons de renvoyer à tout le monde (en fait ça a été corrigé bien plus tôt mais pas régénéré avant).
Pour la version papier, dans une prochaine éventuelle réédition ;)

**Comment by tzi** [comment]
Bien vu :+1:
