### ISSUE TITLE
Images décalées pour les exemples sur `flex: none`

### ISSUE THREAD

**Issue by tzi** [t13h37/feedback-zilliox-flexbox#2]
Lors de la présentation de `flex: none`, 2 exemples de code sont collés l'un à l'autre et les rendus associés sont décalés.

![flexbox](https://user-images.githubusercontent.com/415891/34992635-14c74770-face-11e7-86ad-8d60e90bebf0.jpeg)

**Comment by pouipouidesign** [comment]
Corrigé dans la v1.1 que nous venons de renvoyer à tout le monde.
Pour la version papier, dans une prochaine éventuelle réédition ;)

**Comment by tzi** [comment]
Merci @pouipouidesign :+1:
