### ISSUE TITLE
Image étirée lorsque le container doit faire 50%

### ISSUE THREAD

**Issue by tzi** [t13h37/feedback-zilliox-flexbox#3]
A un moment le conteneur des exemples doit faire 50% de sa largeur nominale.

Les images ont alors été légèrement agrandies, du coup les cellules sont plus haute et on remarque moins leur rétrécissement en largeur. Je trouve que ça peut être perturbant pour le lecteur.

Conteneur à 100%
![capture d ecran de 2018-01-16 16-25-11](https://user-images.githubusercontent.com/415891/34996847-268cb582-fadb-11e7-828e-ef9d9f7139a6.png)

Conteneur à 50%
![capture d ecran de 2018-01-16 16-25-20](https://user-images.githubusercontent.com/415891/34996853-29eeaa5a-fadb-11e7-95e3-aeffe1daef24.png)

**Comment by pouipouidesign** [comment]
Corrigé dans la v1.1 que nous venons de renvoyer à tout le monde.
Pour la version papier, dans une prochaine éventuelle réédition ;)

**Comment by tzi** [comment]
Merci beaucoup @pouipouidesign 
Les 3 schémas de la page 1.3 ont également le même problème.
Désolé de ne pas l'avoir préciser dans le message initial :disappointed:
